obsidian:
  vault_path: /Users/mateo/Documents/mateo-md
  daily_note_pattern: Daily/{date}.md
conditions:
  workout:
    type: checkbox
    pattern: '- [x] Workout'
  writing:
    type: linked_wordcount
    section: Writing
    section_any_level: true
    minimum: 500
auto_unlock:
  enabled: true
  earliest_time: '17:00'
  check_interval: 300
unlock:
  proof_of_work_duration: 7200
  emergency_duration: 300
  emergency_max_per_day: 3
  emergency_initial_wait: 30
  emergency_wait_multiplier: 2
blocked_sites:
- twitter.com
- x.com
- facebook.com
- instagram.com
- reddit.com
- threads.net
- snapchat.com
- pinterest.com
- tumblr.com
- linkedin.com
- tiktok.com
- youtube.com
- twitch.tv
- netflix.com
- hulu.com
- disneyplus.com
- primevideo.com
- news.ycombinator.com
- cnn.com
- foxnews.com
- bbc.com
- nytimes.com
- washingtonpost.com
- theguardian.com
- buzzfeed.com
- 9gag.com
- people.com
- technologyreview.com
- techcrunch.com
- wired.com
- quanta.com
- quantamagazine.org
- primicias.ec
- dotdashmeredith.com
- people.inc
- peacock.tv
remote_sync:
  enabled: true
  blocklist_path: /etc/dnsmasq.d/blocklist.conf
  host: 34.127.22.131
  user: mateo
remote_state:
  enabled: true
  state_path: /etc/block_distractions/state.json
  lock_path: /tmp/block_distractions_state.lock
  use_sudo: true
  timezone: America/Los_Angeles
