# Block Distractions Configuration
# Sensitive settings (vault_path, remote_sync host/user) go in config.secrets.yaml

obsidian:
  # vault_path: Set in config.secrets.yaml
  daily_note_pattern: Daily/{date}.md

conditions:
  workout:
    type: checkbox
    pattern: '- [x] Workout'
  writing:
    type: linked_wordcount
    section: Writing
    section_any_level: true
    minimum: 500

auto_unlock:
  enabled: true
  earliest_time: '17:00'
  check_interval: 300

unlock:
  proof_of_work_duration: 7200
  emergency_duration: 300
  emergency_max_per_day: 3
  emergency_initial_wait: 30
  emergency_wait_multiplier: 2

blocked_sites:
- twitter.com
- x.com
- facebook.com
- instagram.com
- reddit.com
- threads.net
- snapchat.com
- pinterest.com
- tumblr.com
- linkedin.com
- tiktok.com
- youtube.com
- twitch.tv
- netflix.com
- hulu.com
- disneyplus.com
- primevideo.com
- news.ycombinator.com
- cnn.com
- foxnews.com
- bbc.com
- nytimes.com
- washingtonpost.com
- theguardian.com
- buzzfeed.com
- 9gag.com
- people.com
- technologyreview.com
- techcrunch.com
- wired.com
- quanta.com
- quantamagazine.org
- primicias.ec
- dotdashmeredith.com
- people.inc

remote_sync:
  enabled: true
  # host: Set in config.secrets.yaml
  # user: Set in config.secrets.yaml
  blocklist_path: /etc/dnsmasq.d/blocklist.conf
